#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: sample_db
  host: localhost
  pool: 5
  username: postgres
  password: sukasuka

#test:
#  adapter: sqlite3
#  database: db/test.sqlite3
#  pool: 5
#  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: sample_db
  host: localhost
  pool: 5
  username: postgres
  password: sukasuka